apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::478603337655:role/sdmenable_AmazonEKSAutoNodeRole_19june2025
      username: system:node:ip-10-0-135-107.us-west-2.compute.internal
      groups:
        - system:masters
        - system:bootstrappers
        - system:nodes
