apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::478603337655:role/sdmenable_instance_profile_19june2025
      username: sdmenable_user
      groups:
        - system:bootstrappers
        - system:nodes
