# This section creates the roles and role bindings required for identity alias functionality

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sdm-health
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sdm-health-binding
subjects:
- kind: User
  name: sdm-health # Use as the Identity Alias Healthcheck Username
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: sdm-health
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sdm-user-impersonator
rules:
- apiGroups: [""]
  resources: ["users","groups", "serviceaccounts"]
  verbs: ["impersonate"]

---

# User that identity alias impersonates

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fse-sa
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sdm-user-impersonator-binding
subjects:
# Set one of the following, either User or ServiceAccount
- kind: User
  name: fse-sa
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: sdm-user-impersonator
  apiGroup: rbac.authorization.k8s.io


---

  # This creates the roles and role bindings for Discovery functionality

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sdm-discover
rules:
  - apiGroups: [""]
    resources: ["namespaces", "serviceaccounts"]
    verbs: ["list", "get", "watch"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["roles", "rolebindings", "clusterroles", "clusterrolebindings"]
    verbs: ["list", "get", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sdm-discovery-binding
subjects:
- kind: User
  name: discovery
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: sdm-discover
  apiGroup: rbac.authorization.k8s.io
